# language: python
# python:
#   - "3.6.2"

# #Install dependecies
# install:
#   - pip install -r requirements.txt


# #Run tests
# script:
#   - pytest --cov

# after_success:
#   - coveralls

# notifications:
#   email: false


language: python

python: 
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "create database freshs;" -U postgres

script:
  - python -m pytest --cov
  
after_success:
  - coveralls

